### ISSUE TITLE
Ores not pinning with shortcut

### ISSUE THREAD

**Issue by Caledor2000** [searica/DiscoveryPins#1]
It seems like only caves are able to be pinned by the shortcut, and not the ores. Is it possible to make the ores work with the shortcut, and make that a server synced option?

Also, what does section 4 - 4 Auto Pin: Location with the fireplace icon refer to?

**Comment by searica** [comment]
I can pin Copper and Tin ores with the shortcut, so I can't replicate your issue. You need to be looking at them and they should be near the center of your camera view. Also the default keybind requires you to press shift and then left alt and you may need to hold it for a moment as it only checks for the shortcut every 0.1 seconds. I may increase the frequency in the future but I didn't want it running every frame. 

4 Auto Pin: Location refers to places like camps in the plains which are technically dungeons but don't have an interior that you teleport into. The idea is that you can look at the center of a camp and pin it using the shortcut. That part hasn't been as well tested yet though as the mod is still in a bit of a beta release.

**Comment by Caledor2000** [comment]
I'll have to disable some other mods to see if something's causing issues with the copper and tin. I was able to use the shortcut while standing outside of troll caves and crypts, so the keybinds are fine.

Thanks for the info about the camps, etc.

**Comment by Caledor2000** [comment]
I did a bunch of testing, and it looks like the issue was where I was standing and looking when trying to use the shortcuts. If you stand on top of the copper deposit in the middle, and look straight down at it, the shortcut doesn't work. There also seem to be a lot of places you can be looking at it, where it shows the text for the copper deposit, but you can't use the shortcut. But directly on top seems to be the worst spot to do it. It works better the further away from the copper deposit that you are. The tin seems to be fine, it might be that I didn't try it previously with the issues that I was having with the copper.

Silver has the same issue as copper, but since it's so much smaller, it's less of a problem. Obsidian Deposits don't get marked from the shortcut, or doing damage to them.

For the caves, I had said crypts earlier, but I had meant burial chambers. The Sunken Crypts are actually the only caves that don't seem to work. Entering them, or using the shortcut doesn't work.

I tested all of the other types of caves that I could think of, and these all worked with both the shortcut and by entering them:
Troll Cave
Burial Chambers
Frost Cave
Infested Mine
Putrid Hole.

**Comment by searica** [comment]
Yeah, the issue with the auto-pin shortcut is that I have calculate what is "on-screen" and currently for performance reasons the mod only checks a single point per object. For dungeons, it's the entrance which is usually what you're looking at. For ore it's roughly the center of the ore, which can be underground. So you do need to stand back a bit and look down. If you're within 5m of the center it will pin it regardless of your look direction but for larger ores that can be too far away even when standing on them. 

Tin is a lot easier since it's center isn't as deeply underground. I figured that if you're standing on a large chunk of ore you can just punch it to pin it, since you just need to deal damage to it (and 0 damage counts as damage). 

Good to know regarding the Sunken Crypts, thanks for doing the testing and letting me know. I hadn't tested that one. I'm working on another mod currently but I'll try to fix that relatively soon. Also think I'll add auto-pinning to Portals when you build them, use them, and via the shortcut.

**Comment by searica** [comment]
I've just pushed some changes to this repo and updated to version 0.2.0 on Thunderstore. The changes include:
- Fixing auto-pinning functionality for Sunken Crypts
- Allowing auto-pinning when standing very close to objects even if you are not looking at them.
    - This appears to resolve the non-intuitive behaviour that previously existed with larger ores. 
- Auto-pinning of portals when you build them or interact with them.

I think this should resolve all of the issues you found. Please let me know when you get a chance to test version 0.2.0 and can confirm the issues you ran into don't occur anymore.

**Comment by Caledor2000** [comment]
When I tested the new version I noticed that if your character is moving, the shortcut doesn't work. I double checked the old version and moving caused the same issue. So that might have been my main problem when I was trying to pin the ores. I also prefer the original default keybind of Alt+Shift.

There's still a dead zone for the copper, if you're standing on the outer edge and not looking directly at the center, it doesn't work. This can be kind of frustrating, because some copper deposits are buried weirdly where you don't realize the what you're seeing is the edge and not the center.

The shortcut for pinning makes silver way too easy to find. Could that be disabled separately from the other ores, with the option locked by the server?

Obsidian deposits still aren't pinned.

When you enter or exit a portal, it always gets pinned with a default label of "Portal". If it was previously pinned with the tag, there will be a second pin on top of it. If you portal into a portal hub, all of the nearby portals are pinned the the default label.

Sunken Crypts are working perfectly now.

**Comment by searica** [comment]
Yes, you can't be pressing any other keys when using a keyboard shortcut. That is how BepInEx works. If you prefer the old original default then you can change it in the configuration settings.

Regarding copper: That's fair but I'm not inclined to spend more time on it at the moment.

Regarding silver: I'll look into addressing that.

Regarding obsidian: You didn't mention obsidian before as an issue. They have never meant to be pinned as I don't consider them ore. If you want them to be pinned you can either make a separate feature enhancement request or you can make pull request implementing it yourself and I'll consider it.

Regarding portals: I'll see if I can duplicate the issue you're having. That did not occur in my testing.

**Comment by searica** [comment]
See changelog for v0.2.1 and v0.2.2 https://thunderstore.io/c/valheim/p/Searica/DiscoveryPins/changelog/

**Comment by Caledor2000** [comment]
Thanks for the info about how the keybinds work, that makes sense.

The changelogs look like you fixed all the issues, I’ll test this out tomorrow.

Thanks for all the quick updates, I feel like this mod is the perfect blend of auto pinning with a vanilla compatible map.

**Comment by Caledor2000** [comment]
Everything looks good to me, thanks for all the updates!
